# Generated by Django 4.2.5 on 2023-10-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiante_profesor_alter_curso_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
